# Generated by Django 5.0.2 on 2024-03-16 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('order', models.IntegerField()),
                ('rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('brand', models.TextField()),
                ('stall', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('fuel', models.TextField()),
                ('android_carplay', models.BooleanField(default=False)),
                ('touchscreen', models.BooleanField(default=False)),
                ('backup_camera', models.BooleanField(default=False)),
                ('awd', models.BooleanField(default=False)),
                ('high_ground_clearance', models.BooleanField(default=False)),
                ('built_in_navigation', models.BooleanField(default=False)),
                ('keyless_entry', models.BooleanField(default=False)),
                ('leather_seats', models.BooleanField(default=False)),
                ('memory_seat', models.BooleanField(default=False)),
                ('collision_warning', models.BooleanField(default=False)),
                ('lane_keep_assist', models.BooleanField(default=False)),
                ('blind_spot_monitoring', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('sunroof', models.BooleanField(default=False)),
                ('usb_port', models.BooleanField(default=False)),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.car_class')),
            ],
        ),
    ]
