# Generated by Django 5.0.2 on 2024-03-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_Class',
            new_name='Class',
        ),
    ]
