# Generated by Django 5.0.2 on 2024-03-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_license_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
