# Generated by Django 5.0.2 on 2024-03-16 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_car_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
